# =    QuickShop  Configuration   =
# =================================
# 
# Notes:
# Please read the example-configuration.yml file to get a commented example config.

config-version: 149
language: 
game-language: default
dev-mode: false
tax: 0.05
tax-account: tax
unlimited-shop-owner-change: false
unlimited-shop-owner-change-account: quickshop
show-tax: false
respect-item-flag: true
currency: ""
logging: 
   file-size: 10.0
   log-balance: true
   location: 0
   log-actions: true
   enable: true
trying-fix-banlance-insuffient: false
whole-number-prices-only: false
force-bukkit-chat-handler: false
disabled-metrics: false
updater: true
auto-report-errors: true
include-offlineplayer-list: false
economy-type: 0
use-decimal-format: false
decimal-format: '#,###.##'
send-display-item-protection-alert: false
send-shop-protection-alert: false
server-platform: 0
use-caching: true
chat-type: 0
database: 
   mysql: false
   host: localhost
   port: 3306
   database: quickshop
   user: root
   password: passwd
   prefix: none
   usessl: false
   queue: true
   queue-commit-interval: 2
   auto-fix-encoding-issue-in-database: false
limits: 
   use: false
   default: 10
   old-algorithm: false
   ranks: 
      quickshop: 
         example: 20
shop-blocks: 
- CHEST
- TRAPPED_CHEST
- ENDER_CHEST
shop: 
   currency-symbol-on-right: false
   minimum-price: 0.01
   update-sign-when-inventory-moving: false
   enchance-shop-protect: false
   show-owner-uuid-in-controlpanel-if-op: false
   protection-checking-listener-blacklist: 
   - ignored_listener
   display-auto-despawn: false
   allow-stacks: false
   disable-super-tool: false
   sign-material: OAK_WALL_SIGN
   allow-free-shop: false
   sending-stock-message-to-staffs: false
   alternate-currency-symbol-list: 
   - CNY;¥
   - USD;$
   maximum-digits-in-price: -1
   allow-shop-without-space-for-sign: false
   alternate-currency-symbol: $
   lock: true
   force-use-item-original-name: false
   disable-creative-mode-trading: false
   price-restriction: []
   ignore-unlimited-shop-messages: false
   finding: 
      oldLogic: false
      distance: 45
      limit: 10
      all: true
      exclude-out-of-stock: false
   protection-checking-blacklist: 
   - disabled_world
   pay-unlimited-shop-owners: false
   auto-fetch-shop-messages: true
   display-check-time: 40
   display-items-check-ticks: 6000
   price-change-requires-fee: true
   word-for-trade-all-items: all
   refund: false
   sign-dye-color: null
   sign-glowing: false
   display-items: true
   interact: 
      interact-mode: 0
      sneak-to-create: false
      sneak-to-trade: false
      sneak-to-control: false
      swap-click-behavior: false
   protection-checking-handler: 0
   ignore-cancel-chat-event: false
   disable-quick-create: false
   use-enchantment-for-enchanted-book: false
   max-shops-checks-in-once: 100
   use-fast-shop-search-algorithm: 
   auto-sign: true
   enchance-display-protect: false
   cost: 10
   display-type: 2
   protection-checking: true
   remove-protection-trigger: true
   fee-for-price-change: 50
   allow-owner-break-shop-sign: false
   blacklist-world: 
   - disabled_world_name
   force-load-downgrade-items: 
      enable: false
      method: 0
   maximum-price: -1
   allow-economy-loan: false
   display-despawn-range: 20
   display-allow-stacks: false
   blacklist-lores: 
   - SoulBound
   ongoing-fee: 
      enable: false
      ticks: 42000
      cost-per-shop: 2
      ignore-unlimited: true
   disable-vault-format: false
   display-item-use-name: false
blacklist: 
- Bedrock
lockette: 
   enable: true
   private: '[Private]'
   more_users: '[More Users]'
plugin: 
   WorldEdit: true
   BlockHub: 
      enable: true
      only: false
   LWC: true
   NBTAPI: true
   OpenInv: true
   PlaceHolderAPI: true
   Multiverse-Core: true
effect: 
   sound: 
      ontabcomplete: true
      oncommand: true
      onclick: true
matcher: 
   work-type: 0
   item: 
      damage: true
      repaircost: false
      displayname: true
      lores: true
      enchs: true
      potions: true
      attributes: true
      itemflags: true
      custommodeldata: true
      books: true
      banner: true
      skull: true
      firework: true
      map: true
      leatherArmor: true
      fishBucket: true
      suspiciousStew: true
      shulkerBox: true
mixedeconomy: 
   deposit: eco give {0} {1}
   withdraw: eco take {0} {1}
integration: 
   advancedregionmarket: 
      enable: false
   iridiumskyblock: 
      owner-create-only: false
      enable: false
   towny: 
      delete-shop-on-plot-destroy: true
      trade: []
      delete-shop-on-plot-clear: true
      enable: false
      ignore-disabled-worlds: true
      whitelist-mode: true
      create: 
      - SHOPTYPE
      - MODIFY
      delete-shop-on-resident-leave: false
   griefprevention: 
      enable: false
      whitelist-mode: true
      create: INVENTORY
      trade: []
      delete-on-claim-trust-changed: true
      delete-on-claim-unclaimed: true
      delete-on-claim-expired: true
      delete-on-claim-resized: true
      delete-on-subclaim-created: true
   lands: 
      enable: false
      whitelist-mode: false
      ignore-disabled-worlds: true
      delete-on-lose-permission: false
   fabledskyblock: 
      enable: false
      whitelist-mode: false
   plotsquared: 
      enable: false
      whitelist-mode: true
      delete-when-user-untrusted: true
   superiorskyblock: 
      enable: false
      owner-create-only: false
      delete-shop-on-member-leave: true
   residence: 
      enable: false
      whitelist-mode: true
      create: 
      - FLAG
      - interact
      - use
      trade: []
   worldguard: 
      respect-global-region: false
      trade: []
      enable: false
      whitelist-mode: false
      create: 
      - FLAG
      - CHEST_ACCESS
      any-owner: true
   factions: 
      enable: false
      whitelist-mode: true
      create: 
         require: 
            open: false
            normal: true
            wilderness: false
            peaceful: true
            permanent: false
            safezone: false
            own: false
            warzone: false
         flags: 
         - CONTAINER
         - ECONOMY
      trade: 
         require: 
            open: false
            normal: true
            wilderness: false
            peaceful: false
            permanent: false
            safezone: false
            own: false
            warzone: false
         flags: []
protect: 
   explode: true
   hopper: true
   entity: true
custom-item-stacksize: []
debug: 
   disable-debuglogger: false
   shop-deletion: false
   delete-corrupt-shops: false
custom-commands: 
- shop
- chestshop
- cshop
config-damaged: false
server-uuid: 5f7dc58f-a5b6-4437-965d-75092d1585be
legacy-updater: 
   shop-sign: false
mojangapi-mirror: 0
purge: 
   days: 60
   skip-op: true
   banned: true
   return-create-fee: true
   enabled: false
enabled-languages: 
- '*'
disabled-languages: 
logger: 
   location: 0
